SoftwareVillage/Models/ITandCybersecurity.cs
using System.ComponentModel.DataAnnotations;

namespace SoftwareVillage.Models
{
    public class ITandCybersecurity
    {
        [Required]
        public int Id { get; set; }

        public string BlogTitle { get; set; }
        public string BlogSubtitle { get; set; }
        public string SignOfMoney { get; set; }
        public double Payment { get; set; }
        public string Time { get; set; }

        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public string Description5 { get; set; }
    }
}

SoftwareVillage/Areas/AdminPanel/Controllers/ITandCybersecurityController.cs
using SoftwareVillage.Data;
using Microsoft.AspNetCore.Mvc;
using SoftwareVillage.Models;
using Microsoft.EntityFrameworkCore;
using SoftwareVillage.ViewModels;

namespace SoftwareVillage.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class ITandCybersecurityController : Controller
    {
        public readonly SoftwareVillageDbContext _context;
        public ITandCybersecurityController(SoftwareVillageDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
           
            List<ITandCybersecurity> itAndCybersecurities = _context.ITandCybersecurities.ToList();
            return View(itAndCybersecurities);
        }



        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ITandCybersecurity itandCybersecurity)
        {
            if (!ModelState.IsValid) return View();

            bool result = await _context.ITandCybersecurities.AnyAsync(p => p.BlogTitle.Trim().ToLower() == itandCybersecurity.BlogTitle.Trim().ToLower());

            if (result)
            {
                ModelState.AddModelError("Blogtitle", "Eyni adda Kurs artiq movcuddur...");
                return View();
            }
            await _context.ITandCybersecurities.AddAsync(itandCybersecurity);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }






        public async Task<IActionResult> Update(int Id)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }

            ITandCybersecurity old = await _context.ITandCybersecurities.FirstOrDefaultAsync(o => o.Id == Id);
            if (old == null)
            {
                return NotFound();
            }

            return View(old);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int Id, ITandCybersecurity itandCybersecurity)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }

            ITandCybersecurity old = await _context.ITandCybersecurities.FirstOrDefaultAsync(o => o.Id == Id);

            if (old == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            if (old.BlogTitle == itandCybersecurity.BlogTitle && old.BlogSubtitle == itandCybersecurity.BlogSubtitle && old.SignOfMoney == itandCybersecurity.SignOfMoney && old.Payment == itandCybersecurity.Payment && old.Time == itandCybersecurity.Time && old.Description1 == itandCybersecurity.Description1 && old.Description2 == itandCybersecurity.Description2 && old.Description3 == itandCybersecurity.Description3 && old.Description4 == itandCybersecurity.Description4 && old.Description5 == itandCybersecurity.Description5)
            {
                await Console.Out.WriteLineAsync("Hec bir deyisiklik etmediniz.");
                return RedirectToAction(nameof(Index));

            }

            bool result = await _context.ITandCybersecurities.AnyAsync(p => p.BlogTitle.Trim().ToLower() == itandCybersecurity.BlogTitle.Trim().ToLower() && p.Id != old.Id);
            if (result)
            {
                ModelState.AddModelError("BlogTitle", "Bu adda kurs basligi artiq var");
                return View(old);
            }

            old.BlogTitle = itandCybersecurity.BlogTitle;
            old.BlogSubtitle = itandCybersecurity.BlogSubtitle;
            old.SignOfMoney = itandCybersecurity.SignOfMoney;
            old.Payment = itandCybersecurity.Payment;
            old.Time = itandCybersecurity.Time;
            old.Description1 = itandCybersecurity.Description1;
            old.Description2 = itandCybersecurity.Description2;
            old.Description3 = itandCybersecurity.Description3;
            old.Description4 = itandCybersecurity.Description4;
            old.Description5 = itandCybersecurity.Description5;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }




        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }
            ITandCybersecurity itandCybersecurity = await _context.ITandCybersecurities.FirstOrDefaultAsync(o => o.Id == Id);
            if (itandCybersecurity == null) NotFound();

            _context.ITandCybersecurities.Remove(itandCybersecurity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }


    }
}

SoftwareVillage/Areas/AdminPanel/Views/ITandCybersecurity/Create.cshtml
@using SoftwareVillage.Models;
@model ITandCybersecurity

<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Kurs əlavə et</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="BlogTitle">
                        Kurs başlığı
                    </label>
                    <input asp-for="BlogTitle" type="text" class="form-control" placeholder="Kurs başlığı" />
                    <span asp-validation-for="BlogTitle"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BlogSubtitle">
                        Kurs altbaşlığı
                    </label>
                    <input asp-for="BlogSubtitle" type="text" class="form-control" placeholder="Kurs altbaşlığı" />
                    <span asp-validation-for="BlogSubtitle"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SignOfMoney">
                        Pul nişanı
                    </label>
                    <input asp-for="SignOfMoney" type="text" class="form-control" placeholder="Pul nişanı" />
                    <span asp-validation-for="SignOfMoney"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Payment">
                        Ödəniş
                    </label>
                    <input asp-for="Payment" type="number" class="form-control" placeholder="Ödəniş" />
                    <span asp-validation-for="Payment"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Time">
                        Müddət
                    </label>
                    <input asp-for="Time" type="text" class="form-control" placeholder="Müddət" />
                    <span asp-validation-for="Time"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description1">
                        Təsvir1
                    </label>
                    <input asp-for="Description1" type="text" class="form-control" placeholder="Təsvir" />
                    <span asp-validation-for="Description1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description2">
                        Təsvir2
                    </label>
                    <input asp-for="Description2" type="text" class="form-control" placeholder="Təsvir" />
                    <span asp-validation-for="Description2"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description3">
                        Təsvir3
                    </label>
                    <input asp-for="Description3" type="text" class="form-control" placeholder="Təsvir" />
                    <span asp-validation-for="Description3"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description4">
                        Təsvir4
                    </label>
                    <input asp-for="Description4" type="text" class="form-control" placeholder="Təsvir" />
                    <span asp-validation-for="Description4"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description5">
                        Təsvir5
                    </label>
                    <input asp-for="Description5" type="text" class="form-control" placeholder="Təsvir" />
                    <span asp-validation-for="Description5"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Yadda saxla</button>
                <button class="btn btn-light">Ləğv et</button>
            </form>
        </div>
    </div>
</div>

SoftwareVillage/Areas/AdminPanel/Views/ITandCybersecurity/Index.cshtml
@using SoftwareVillage.Models;
@model List<ITandCybersecurity>

@{
    int count = 1;
}

<div class="col-lg-12 grid-margin stretch-card">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Kurs əlave et</h4>

            <a asp-controller="ITandCybersecurity" asp-action="Create" type="button" class="btn btn-info">Kurs əlave et</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Sıra nömrəsi
                            </th>
                            <th>
                                Başlıq
                            </th>
                            <th>
                                Altbaşlıq
                            </th>
                            <th>
                                Pul ikonu
                            </th>
                            <th>
                                Ödəniş miqdarı
                            </th>
                            <th>
                                Müddət
                            </th>
                            <th>
                                Təsvir1
                            </th>
                            <th>
                                Təsvir2
                            </th>
                            <th>
                                Təsvir3
                            </th>
                            <th>
                                Təsvir4
                            </th>
                            <th>
                                Təsvir5
                            </th>
                            <th>
                                Ayarlar
                            </th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (ITandCybersecurity item in Model)
                        {
                            <tr>
                                <td>
                                    @(count++)
                                </td>
                                <td>
                                    @item.BlogTitle
                                </td>
                                <td>
                                    @item.BlogSubtitle
                                </td>
                                <td>
                                    @item.SignOfMoney
                                </td>
                                <td>
                                    @item.Payment
                                </td>
                                <td>
                                    @item.Time
                                </td>
                                <td>
                                    @item.Description1
                                </td>
                                <td>
                                    @item.Description2
                                </td>
                                <td>
                                    @item.Description3
                                </td>
                                <td>
                                    @item.Description4
                                </td>
                                <td>
                                    @item.Description5
                                </td>
                                <td>
                                    <a asp-controller="ITandCybersecurity" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-grease-pencil"></i></a>
                                    <a asp-controller="ITandCybersecurity" asp-action="delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SoftwareVillage/Areas/AdminPanel/Views/ITandCybersecurity/Update.cshtml
@using SoftwareVillage.Models
@model ITandCybersecurity

<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Redaktə et</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="BlogTitle">
                        Kurs başlığı
                    </label>
                    <input asp-for="BlogTitle" type="text" class="form-control" placeholder="Kurs başlığı" value="@Model.BlogTitle" />
                    <span asp-validation-for="BlogTitle"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BlogSubtitle">
                        Kurs altbaşlığı
                    </label>
                    <input asp-for="BlogSubtitle" type="text" class="form-control" placeholder="Kurs altbaşlığı" value="@Model.BlogSubtitle" />
                    <span asp-validation-for="BlogSubtitle"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SignOfMoney">
                        Pul nişanı
                    </label>
                    <input asp-for="SignOfMoney" type="text" class="form-control" placeholder="Pul nişanı" value="@Model.SignOfMoney" />
                    <span asp-validation-for="SignOfMoney"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Payment">
                        Ödəniş
                    </label>
                    <input asp-for="Payment" type="number" class="form-control" placeholder="Ödəniş" value="@Model.Payment" />
                    <span asp-validation-for="Payment"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Time">
                        Müddət
                    </label>
                    <input asp-for="Time" type="text" class="form-control" placeholder="Müddət" value="@Model.Time" />
                    <span asp-validation-for="Time"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description1">
                        Təsvir1
                    </label>
                    <input asp-for="Description1" type="text" class="form-control" placeholder="Təsvir1" value="@Model.Description1" />
                    <span asp-validation-for="Description1"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description2">
                        Təsvir2
                    </label>
                    <input asp-for="Description2" type="text" class="form-control" placeholder="Təsvir2" value="@Model.Description2" />
                    <span asp-validation-for="Description2"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description3">
                        Təsvir3
                    </label>
                    <input asp-for="Description3" type="text" class="form-control" placeholder="Təsvir3" value="@Model.Description3" />
                    <span asp-validation-for="Description3"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description4">
                        Təsvir4
                    </label>
                    <input asp-for="Description4" type="text" class="form-control" placeholder="Təsvir4" value="@Model.Description4" />
                    <span asp-validation-for="Description4"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description5">
                        Təsvir5
                    </label>
                    <input asp-for="Description5" type="text" class="form-control" placeholder="Təsvir5" value="@Model.Description5" />
                    <span asp-validation-for="Description5"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Yadda saxla</button>
                <button class="btn btn-light">Ləğv et</button>
            </form>
        </div>
    </div>
</div>