SoftwareVillage/Models/It_SoftwareVillage.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SoftwareVillage.Models
{
    public class It_SoftwareVillage
    {
        [Required]
        public int Id { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }

        public string LittleTitle { get; set; }
        public string BigTitle { get; set; }
    }
}

SoftwareVillage/Areas/AdminPanel/Controllers/It_SoftwareVillageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoftwareVillage.Data;
using SoftwareVillage.Models;
using SoftwareVillage.ViewModels;


namespace SoftwareVillage.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class It_SoftwareVillageController : Controller
    {
        private readonly SoftwareVillageDbContext _context;
        private readonly IWebHostEnvironment _env;
        public It_SoftwareVillageController(SoftwareVillageDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            List<It_SoftwareVillage> it_SoftwareVillages = _context.it_SoftwareVillages.ToList();

            return View(it_SoftwareVillages);
        }
        public IActionResult Create()
        {

            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Create(It_SoftwareVillage it_SoftwareVillage)
        {

            if (!ModelState.IsValid) return View();

            if (it_SoftwareVillage == null)

            {
                ModelState.AddModelError("Photo", "Sekil Secilmeyib");
                return View();

            }

            if (!it_SoftwareVillage.Photo.ContentType.Contains("image/"))
            {
                ModelState.AddModelError("Photo", "Tipi sehvdir");
                return View();

            }


            if (it_SoftwareVillage.Photo.Length / 1024 > 200)
            {
                ModelState.AddModelError("Photo", "Olcu Odemir");
                return View();
            }

            var filename = Guid.NewGuid().ToString() + "_" + it_SoftwareVillage.Photo.FileName;
            it_SoftwareVillage.Image = filename;
            string path = Path.Combine(_env.WebRootPath, "assets/img", filename);
            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await it_SoftwareVillage.Photo.CopyToAsync(stream);
            }
            await _context.it_SoftwareVillages.AddAsync(it_SoftwareVillage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Update(int id)
        {
            if (id == null || id < 1)
            {
                return BadRequest();

            }
            It_SoftwareVillage news = await _context.it_SoftwareVillages.FirstOrDefaultAsync(n => n.Id == id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }





        [HttpPost]
        public async Task<IActionResult> Update(It_SoftwareVillage it_SoftwareVillage)
        {
            if (!ModelState.IsValid) return View();

            It_SoftwareVillage old = await _context.it_SoftwareVillages.FirstOrDefaultAsync(o => o.Id == it_SoftwareVillage.Id);
            if (old == null)
            {
                return NotFound();
            }


            if (it_SoftwareVillage.Photo != null)
            {
                if (!it_SoftwareVillage.Photo.ContentType.Contains("image/"))
                {
                    ModelState.AddModelError("Photo", "Sekil tipi duzgun deyil");
                    return View();
                }
                if (it_SoftwareVillage.Photo.Length / 1024 > 200)
                {
                    ModelState.AddModelError("Photo", "Olcu duzgun deyil");
                    return View();
                }


            }


            string path = Path.Combine(_env.WebRootPath + "img" + old.Image);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            var fileName = Guid.NewGuid().ToString() + "" + it_SoftwareVillage.Photo.FileName;
            old.Image = fileName;

            string newpath = Path.Combine(_env.WebRootPath, "assets/img", fileName);
            using (FileStream stream = new FileStream(newpath, FileMode.Create))
            {
                await it_SoftwareVillage.Photo.CopyToAsync(stream);
            }

            old.BigTitle = it_SoftwareVillage.BigTitle;
            old.LittleTitle = it_SoftwareVillage.LittleTitle;




            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || id < 1)
            {
                return BadRequest();
            }
            It_SoftwareVillage news = await _context.it_SoftwareVillages.FirstOrDefaultAsync(n => n.Id == id);
            if (news == null)
            {
                return NotFound();
            }
            string path = Path.Combine(_env.WebRootPath + "img" + news.Image);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            _context.it_SoftwareVillages.Remove(news);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
    }
}

SoftwareVillage/Areas/AdminPanel/Views/It_SoftwareVillage/Create.cshtml
@using SoftwareVillage.Models;
@model It_SoftwareVillage

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Haqqımızda</h4>
                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label asp-for="Photo">Şəkil</label>
                                <input asp-for="Photo" type="file" class="form-control" placeholder="Photo" />

                                <span asp-validation-for="Photo"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BigTitle">Başlıq</label>
                                <input asp-for="BigTitle" type="text" class="form-control" placeholder="Başlıq" />
                            </div>

                            <div class="form-group">
                                <label asp-for="LittleTitle">Altbaşlıq</label>
                                <input asp-for="LittleTitle" type="text" class="form-control" placeholder="Altbaşlıq" />
                            </div>


                            <button type="submit" class="btn btn-primary me-2">Yadda saxla</button>
                            <button class="btn btn-light">Ləğv et</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SoftwareVillage/Areas/AdminPanel/Views/It_SoftwareVillage/Index.cshtml
@using SoftwareVillage.Models;
@model List<It_SoftwareVillage>

@{
    int count = 1;
}

<div class="col-lg-12 grid-margin stretch-card">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Haqqimizda</h4>

            <a asp-controller="It_SoftwareVillage" asp-action="Create" type="button" class="btn btn-info">Yarat</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Sıra Nömrəsi
                            </th>
                            <th>
                                Şəkil
                            </th>
                            <th>
                                Başlıq
                            </th>
                            <th>
                                Altbaşlıq
                            </th>
                            <th>
                                Ayarlar
                            </th>
                        </tr>
                    </thead>

                    <tbody>


                        @foreach (It_SoftwareVillage item in Model)
                        {
                            <tr>
                                <td>
                                    @(count++)
                                </td>
                                <td class="py-1">
                                    <img src="~/assets/img/@item.Image" alt="image" />
                                </td>
                                <td>
                                    @item.BigTitle
                                </td>
                                <td>
                                    @item.LittleTitle
                                </td>
                                <td>
                                    <a asp-controller="It_SoftwareVillage" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-grease-pencil"></i></a>
                                    <a asp-controller="It_SoftwareVillage" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SoftwareVillage/Areas/AdminPanel/Views/It_SoftwareVillage/Update.cshtml
@using SoftwareVillage.Models;
@model It_SoftwareVillage

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Redaktə et</h4>
                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div>
                                <img src="~/assets/img/@Model.Image" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" type="file" class="form-control" placeholder="photo" />

                                <span asp-validation-for="Photo"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="BigTitle">Title</label>
                                <input asp-for="BigTitle" type="text" class="form-control" value="@Model.BigTitle" placeholder="Name" />
                            </div>
                            <div class="form-group">
                                <label asp-for="LittleTitle">Subtitle</label>
                                <input asp-for="LittleTitle" type="text" class="form-control" value="@Model.LittleTitle" placeholder="Name" />
                            </div>



                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>