SoftwareVillage/Areas/AdminPanel/Controllers/VizyonController.cs
using SoftwareVillage.Data;
using Microsoft.AspNetCore.Mvc;
using SoftwareVillage.Models;
using Microsoft.EntityFrameworkCore;

namespace SoftwareVillage.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class VizyonController : Controller
    {
        public readonly SoftwareVillageDbContext _context;
        public VizyonController(SoftwareVillageDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Missiyamız> missiyamız = _context.Missiyamız.ToList();
            return View(missiyamız);
        }



        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Missiyamız missiyamiz)
        {
            if (!ModelState.IsValid) return View();

            bool result = await _context.Missiyamız.AnyAsync(p => p.Title.Trim().ToLower() == missiyamiz.Title.Trim().ToLower());

            if (result)
            {
                ModelState.AddModelError("Blogtitle", "Eyni adda Kurs artiq movcuddur...");
                return View();
            }
            await _context.Missiyamız.AddAsync(missiyamiz);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }






        public async Task<IActionResult> Update(int Id)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }

            Missiyamız old = await _context.Missiyamız.FirstOrDefaultAsync(o => o.Id == Id);
            if (old == null)
            {
                return NotFound();
            }

            return View(old);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int Id, Missiyamız missiyamız)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }

            Missiyamız old = await _context.Missiyamız.FirstOrDefaultAsync(o => o.Id == Id);

            if (old == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            if (old.Title == missiyamız.Title && old.Subtitle == missiyamız.Subtitle && old.Controller_Name == missiyamız.Controller_Name && old.View_Name == missiyamız.Controller_Name)
            {


                return RedirectToAction(nameof(Index));

            }

            bool result = await _context.Missiyamız.AnyAsync(p => p.Title.Trim().ToLower() == missiyamız.Title.Trim().ToLower() && p.Id != old.Id);
            if (result)
            {
                ModelState.AddModelError("BlogTitle", "Bu adda kurs basligi artiq var");
                return View(old);
            }

            old.Title = missiyamız.Title;
            old.Subtitle = missiyamız.Subtitle;
            old.Controller_Name = missiyamız.Controller_Name;
            old.View_Name = missiyamız.View_Name;
            
          

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }




        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }
            Missiyamız missiyamiz = await _context.Missiyamız.FirstOrDefaultAsync(o => o.Id == Id);
            if (missiyamiz == null) NotFound();

            _context.Missiyamız.Remove(missiyamiz);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }


    }
}

SoftwareVillage/Areas/AdminPanel/Views/Vizyon/Create.cshtml
@using SoftwareVillage.Models;
@model Missiyamız

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Missiyamız</h4>
                        <form class="forms-sample" method="post" enctype="multipart/form-data">
@* 
                            <div class="form-group">
                                <label asp-for="Icon">Ikon</label>
                                <input asp-for="Icon" type="text" class="form-control" placeholder="Haqqında" />
                            </div> *@

                            <div class="form-group">
                                <label asp-for="Title">Title</label>
                                <input asp-for="Title" type="text" class="form-control" placeholder="Başlıq" />
                            </div>

                            <div class="form-group">
                                <label asp-for="Subtitle">Subtitle</label>
                                <input asp-for="Subtitle" type="text" class="form-control" placeholder="Altbaşlıq" />
                            </div>

                            <div class="form-group">
                                <label asp-for="Controller_Name">Kurs adı</label>
                                <input asp-for="Controller_Name" type="text" class="form-control" placeholder="Təsvir1" />
                            </div>
                            <div class="form-group">
                                <label asp-for="View_Name">Index</label>
                                <input asp-for="View_Name" type="text" class="form-control" placeholder="Təsvir1" />
                            </div>
                            <button type="submit" class="btn btn-primary me-2">Yadda saxla</button>
                            <button class="btn btn-light">Ləğv et</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SoftwareVillage/Areas/AdminPanel/Views/Vizyon/Index.cshtml
@using SoftwareVillage.Models;
@model List<Missiyamız>

@{
    int count = 1;
}

<div class="col-lg-12 grid-margin stretch-card">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Vizyonumuz</h4>

            <a asp-controller="Vizyon" asp-action="Create" type="button" class="btn btn-info">Yarat</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Sıra nömrəsi
                            </th>
                            @* <th title="Font Awesome saytına daxil olun.Icons bölməsini seçin, Iconun qısa kodunu kopyalayıb yapışdırın. ">
                                Ikon
                            </th> *@

                            <th>
                                Başlıq
                            </th>
                            <th>
                                Altbaşlıq
                            </th>
                            <th>
                                Kurs adı
                            </th>
                            <th>
                                Index
                            </th>
                            
                            <th>
                                Ayarlar
                            </th>
                        </tr>
                    </thead>

                    <tbody>


                       @foreach (Missiyamız item in Model)
                        {
                            <tr>
                                <td>
                                    @(count++)
                                </td>
                               @*  <td title="Font Awesome saytına daxil olun.Icons bölməsini seçin, Iconun qısa kodunu kopyalayıb yapışdırın.">
                                    
                                        <i class="@item.Icon"></i>
                                    
                                </td> *@

                                <td>
                                    @item.Title
                                </td>
                                <td>
                                    @item.Subtitle
                                </td>
                                <td>
                                    @item.Controller_Name
                                </td>
                                <td>
                                    @item.View_Name
                                </td>
                                <td>
                                    <a asp-controller="Vizyon" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-grease-pencil"></i></a>
                                    <a asp-controller="Vizyon" asp-action="delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="https://kit.fontawesome.com/65d861d288.js" crossorigin="anonymous"></script>

SoftwareVillage/Areas/AdminPanel/Views/Vizyon/Update.cshtml
@using SoftwareVillage.Models;
@model Missiyamız

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Redaktə et</h4>
                        <form class="forms-sample" method="post" enctype="multipart/form-data">

@*                             <div class="form-group">
                                <label asp-for="Icon">Ikon</label>
                                <input asp-for="Icon" type="text" class="form-control" value="@Model.Icon" placeholder="Ikon" />
                            </div> *@
                            <div class="form-group">
                                <label asp-for="Title">Başlıq</label>
                                <input asp-for="Title" type="text" class="form-control" value="@Model.Title" placeholder="Başlıq" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Subtitle">Altbaşlıq</label>
                                <input asp-for="Subtitle" type="text" class="form-control" value="@Model.Subtitle" placeholder="Altbaşlıq" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Controller_Name">Kurs adı</label>
                                <input asp-for="Controller_Name" type="text" class="form-control" value="@Model.Controller_Name" placeholder="Kurs adı" />
                            </div>
                            <div class="form-group">
                                <label asp-for="View_Name">Index</label>
                                <input asp-for="View_Name" type="text" class="form-control" value="@Model.View_Name" placeholder="İndex" />
                            </div>
                            
                            <button type="submit" class="btn btn-primary me-2">Yadda saxla</button>
                            <button class="btn btn-light">Ləğv et</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>