SoftwareVillage/Models/StudentFeedbacks.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SoftwareVillage.Models
{
    public class StudentFeedbacks
    {
        [Required]
        public int Id { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }

        public string FullName { get; set; }

        public int BootcampId { get; set; }
        public Bootcamps Bootcamp { get; set; }

        public string Feedbacks {  get; set; }

        public StudentFeedbacks()
        {

        }
    }
}

SoftwareVillage/Areas/AdminPanel/Controllers/StudentFeedbacksController.cs
using SoftwareVillage.Data;
using SoftwareVillage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Security.Cryptography;

namespace SoftwareVillage.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class StudentFeedbacksController : Controller
    {
        public readonly SoftwareVillageDbContext _context;
        private readonly IWebHostEnvironment _env;

        public StudentFeedbacksController(SoftwareVillageDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;

        }

        public async Task<IActionResult> Index()
        {
            List<StudentFeedbacks> person = await _context.studentsFeedbacks
                .Include(p => p.Bootcamp)
                .ToListAsync();

            return View(person);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Bootcamps = await _context.bootcamps.ToListAsync();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(StudentFeedbacks studentFeedbacks)
        {
            bool result = await _context.studentsFeedbacks.AnyAsync(p => p.Id == studentFeedbacks.BootcampId);

            if (!result)
            {
                ModelState.AddModelError("ProfessionId", "Bele vezife yoxdur");
                ViewBag.StudentsFeedbacks = await _context.studentsFeedbacks.ToListAsync();
                return View();
            }

            if (studentFeedbacks == null)

            {
                ModelState.AddModelError("Photo", "Sekil Secilmeyib");
                return View();

            }

            if (!studentFeedbacks.Photo.ContentType.Contains("image/"))
            {
                ModelState.AddModelError("Photo", "Tipi sehvdir");
                return View();

            }


            if (studentFeedbacks.Photo.Length / 1024 > 200)
            {
                ModelState.AddModelError("Photo", "Olcu Odemir");
                return View();
            }

            var filename = Guid.NewGuid().ToString() + "_" + studentFeedbacks.Photo.FileName;
            studentFeedbacks.Image = filename;
            string path = Path.Combine(_env.WebRootPath, "assets/img", filename);
            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await studentFeedbacks.Photo.CopyToAsync(stream);
            }
            

            await _context.studentsFeedbacks.AddAsync(studentFeedbacks);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Update(int Id)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }

            StudentFeedbacks exit = await _context.studentsFeedbacks.FirstOrDefaultAsync(p => p.Id == Id);
            if (exit == null)
            {
                return NotFound();
            }
            ViewBag.Bootcamps = await _context.bootcamps.ToListAsync();


            return View(exit);

        }

        [HttpPost]
        public async Task<IActionResult> Update(int Id, StudentFeedbacks studentFeedbacks)
        {
            if (Id == null || Id < 1)
            {
                return BadRequest();
            }

            StudentFeedbacks exit = await _context.studentsFeedbacks.FirstOrDefaultAsync(p => p.Id == Id);
            if (exit == null)
            {
                return NotFound();
            }

            bool result = await _context.studentsFeedbacks.AnyAsync(p => p.Id == studentFeedbacks.BootcampId);
            if (!result)
            {
                ModelState.AddModelError("ProfessionId", "Bele vezife yoxdur");
                ViewBag.StudentsFeedbacks = await _context.studentsFeedbacks.ToListAsync();
                return View();
            }
            if (studentFeedbacks.Photo != null)
            {
                if (!studentFeedbacks.Photo.ContentType.Contains("image/"))
                {
                    ModelState.AddModelError("Photo", "Sekil tipi duzgun deyil");
                    return View();
                }
                if (studentFeedbacks.Photo.Length / 1024 > 200)
                {
                    ModelState.AddModelError("Photo", "Olcu duzgun deyil");
                    return View();
                }
            }


            string path = Path.Combine(_env.WebRootPath + "img" + exit.Image);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            var fileName = Guid.NewGuid().ToString() + "" + studentFeedbacks.Photo.FileName;
            exit.Image = fileName;

            string newpath = Path.Combine(_env.WebRootPath, "assets/img", fileName);
            using (FileStream stream = new FileStream(newpath, FileMode.Create))
            {
                await studentFeedbacks.Photo.CopyToAsync(stream);
            }

            exit.FullName = studentFeedbacks.FullName;
            exit.BootcampId = studentFeedbacks.BootcampId;
            exit.Feedbacks = studentFeedbacks.Feedbacks;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Delete(int Id)
        {
            if (!ModelState.IsValid) return View();

            StudentFeedbacks person = await _context.studentsFeedbacks.FirstOrDefaultAsync(p => p.Id == Id);

            if (person == null) return NotFound();
            string path = Path.Combine(_env.WebRootPath + "img" + person.Image);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
           
            _context.studentsFeedbacks.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

SoftwareVillage/Areas/AdminPanel/Views/StudentFeedbacks/Create.cshtml
@using SoftwareVillage.Models;
@model StudentFeedbacks

<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Əlavə et</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Photo">Şəkil</label>
                    <input asp-for="Photo" type="file" class="form-control" placeholder="Şəkil" />

                    <span asp-validation-for="Photo"></span>
                </div>
                @* <div class="form-group">
                    <label asp-for="Image">
                        Şəkil
                    </label>
                    <input asp-for="Image" type="text" class="form-control" placeholder="Şəkil" />
                    <span asp-validation-for="Image"></span>
                </div> *@

                <div class="form-group">
                    <label asp-for="FullName">
                        Ad və Soyad
                    </label>
                    <input asp-for="FullName" type="text" class="form-control" placeholder="Ad və Soyad" />
                    <span asp-validation-for="FullName"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BootcampId">
                        Bootkamp
                    </label>
                    <select asp-for="BootcampId">
                        <option selected disabled>Seçim</option>
                        @foreach (Bootcamps item in ViewBag.Bootcamps)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }

                        <span asp-validation-for="BootcampId"></span>
                    </select>

                </div>

                <div class="form-group">
                    <label asp-for="Feedbacks">
                        Rəy
                    </label>
                    <input asp-for="Feedbacks" type="text" class="form-control" placeholder="Rəy" />
                    <span asp-validation-for="Feedbacks"></span>
                </div>

                <button type="submit" class="btn btn-primary me-2">Yadda saxla</button>
                <button class="btn btn-light">Ləğv et</button>

            </form>

        </div>
    </div>
</div>

SoftwareVillage/Areas/AdminPanel/Views/StudentFeedbacks/Index.cshtml
@using SoftwareVillage.Models;
@model List<StudentFeedbacks>

@{
    int count = 1;
}

<div class="col-lg-12 grid-margin stretch-card">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Əlavə et</h4>

            <a asp-controller="StudentFeedbacks" asp-action="Create" type="button" class="btn btn-info">Şəxs əlavə et</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Sıra nömrəsi
                            </th>
                            <th>
                                Şəkil
                            </th>
                            <th>
                                Ad və Soyad
                            </th>
                            <th>
                                Bootkamp
                            </th>
                            <th>
                                Rəy
                            </th>
                            <th>
                                Setting
                            </th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (StudentFeedbacks item in Model)
                        {
                            <tr>
                                <td>
                                    @(count++)
                                </td>

                                <td class="py-1">
                                    <img src="~/assets/img/@item.Image" alt="image" />
                                </td>

                                <td>
                                    @item.FullName
                                </td>
                                <td>
                                    @item.Bootcamp.Name
                                </td>
                                <td>
                                    @item.Feedbacks
                                </td>
                                <td>
                                    <a asp-controller="StudentFeedbacks" asp-action="update" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-grease-pencil"></i></a>
                                    <a asp-controller="StudentFeedbacks" asp-action="delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SoftwareVillage/Areas/AdminPanel/Views/StudentFeedbacks/Update.cshtml
@using SoftwareVillage.Models;
@model StudentFeedbacks

<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Əlavə et</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">

                <div>
                    <img src="~/assets/img/@Model.Image" />
                </div>
                <div class="form-group">
                    <label asp-for="Photo">Şəkil</label>
                    <input asp-for="Photo" type="file" class="form-control" placeholder="Şəkil" />

                    <span asp-validation-for="Photo"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FullName">
                        Ad və Soyad
                    </label>
                    <input asp-for="FullName" type="text" class="form-control" placeholder="Ad və Soyad" value="@Model.FullName" />
                    <span asp-validation-for="FullName"></span>
                </div>

                
                <div class="form-group">
                    <label asp-for="BootcampId">
                        Bootkamp
                    </label>
                    <select asp-for="BootcampId">
                        <option selected disabled>Seçim</option>
                        @foreach (Bootcamps item in ViewBag.Bootcamps)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }

                        <span asp-validation-for="BootcampId"></span>
                    </select>

                </div>
                <div class="form-group">
                    <label asp-for="Feedbacks">
                        Rəy
                    </label>
                    <input asp-for="Feedbacks" type="text" class="form-control" placeholder="Rəy" value="@Model.Feedbacks" />
                    <span asp-validation-for="Feedbacks"></span>
                </div>

                <button type="submit" class="btn btn-primary me-2">Yadda saxla</button>
                <button class="btn btn-light">Ləğv et</button>

            </form>

        </div>
    </div>
</div>